// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDqrfwWxDys6QNXlQiBtlowzKXUf04Oms',
    appId: '1:257099322914:web:306f50c155a20897849c7b',
    messagingSenderId: '257099322914',
    projectId: 'greenbin-a6830',
    authDomain: 'greenbin-a6830.firebaseapp.com',
    storageBucket: 'greenbin-a6830.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEbutBaUXrk6CL7659c7mnO8cNqoc2uQo',
    appId: '1:257099322914:android:0cc505d435023405849c7b',
    messagingSenderId: '257099322914',
    projectId: 'greenbin-a6830',
    storageBucket: 'greenbin-a6830.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjE_AJYU91Nr1ZALQLyNszP9PhBAHpAOc',
    appId: '1:257099322914:ios:bfe5314d7e5c02f5849c7b',
    messagingSenderId: '257099322914',
    projectId: 'greenbin-a6830',
    storageBucket: 'greenbin-a6830.firebasestorage.app',
    iosBundleId: 'com.example.easytrash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjE_AJYU91Nr1ZALQLyNszP9PhBAHpAOc',
    appId: '1:257099322914:ios:bfe5314d7e5c02f5849c7b',
    messagingSenderId: '257099322914',
    projectId: 'greenbin-a6830',
    storageBucket: 'greenbin-a6830.firebasestorage.app',
    iosBundleId: 'com.example.easytrash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDqrfwWxDys6QNXlQiBtlowzKXUf04Oms',
    appId: '1:257099322914:web:5f970f379521e548849c7b',
    messagingSenderId: '257099322914',
    projectId: 'greenbin-a6830',
    authDomain: 'greenbin-a6830.firebaseapp.com',
    storageBucket: 'greenbin-a6830.firebasestorage.app',
  );
}
